# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.cache/wt [current_project]
set_property parent.project_path C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/IP_srcs/charLib.coe
add_files -quiet C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/instr_mem_synth_1/instr_mem.dcp
set_property used_in_implementation false [get_files C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/instr_mem_synth_1/instr_mem.dcp]
add_files -quiet C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/vio_0_synth_1/vio_0.dcp
set_property used_in_implementation false [get_files C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/vio_0_synth_1/vio_0.dcp]
add_files -quiet C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/data_memory_synth_1/data_memory.dcp
set_property used_in_implementation false [get_files C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/data_memory_synth_1/data_memory.dcp]
add_files -quiet C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/charLib_synth_1/charLib.dcp
set_property used_in_implementation false [get_files C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.runs/charLib_synth_1/charLib.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/new/pc_counter.v
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/imports/new/inst_decoder.v
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/imports/Downloads/debounce.v
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/imports/Downloads/lab5-20170321T131117Z-001/lab5/lab5.srcs/sources_1/imports/leclair.m/Desktop/reg_file.v
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/imports/Downloads/lab5-20170321T131117Z-001/lab5/lab5.srcs/sources_1/imports/leclair.m/Desktop/eightbit_palu.v
  C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/imports/liang.vi/Downloads/datapath_top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/Delay.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/BINBCD8.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/SpiCtrl.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/SIGNDET.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/OledInit.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/OledExample.vhd
  C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/HDLs/PmodOLEDCtrl.vhd
}
read_xdc C:/Users/leclair.m.NUNET/Downloads/datapath.xdc
set_property used_in_implementation false [get_files C:/Users/leclair.m.NUNET/Downloads/datapath.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top datapath_top -part xc7z020clg484-1
write_checkpoint -noxdef datapath_top.dcp
catch { report_utilization -file datapath_top_utilization_synth.rpt -pb datapath_top_utilization_synth.pb }
