# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/leclair.m.NUNET/Downloads/OLED_source_files/OLED_source_files/IP_srcs/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]

# XDC: C:/Users/leclair.m.NUNET/Downloads/datapath.xdc
