# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/ip/instr_mem/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/ip/instr_mem/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/ip/instr_mem/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/leclair.m.NUNET/Downloads/lab7completed/lab7completed/lab7completed.srcs/sources_1/ip/instr_mem/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
